name: Tag CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-pack-push:
    name: Build, Pack, Push
    uses: n3oltd/actions/.github/workflows/dotnet-build-pack-push.yml@main
    with:
      run-tests: false
      run-pack: true
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
